on: push
name: Deploy website on push
jobs:
web-deploy:
name: testvvvvvvvvvvvvv.000webhostapp.com
runs-on: ubuntu-latest
steps:
- name: Get latest code
uses: actions/checkout@v3
- name: Sync files
uses: SamKirkland/FTP-Deploy-Action@4.3.3
with:
server: testvvvvvvvvvvvvv.000webhostapp.com
username: ahmedarfaoui1600
password: THrjBT8KviwmpUNxgauE
server-dir : public_html/
